Notion/c37 Add velas chain
KyberNetwork/dmm-interface pull request #832
Opened 2022-03-02 17:10 UTC by namgold

2022-03-03 02:04 UTC, viet-nv requested changes

2022-03-03 02:04 UTC, viet-nv commented on src/constants/dexes.ts
> +  },
remember update these information, 2 new dexes and 1 new chain
<img width="507" alt="image" src="https://user-images.githubusercontent.com/11427213/156482085-a777d37a-8c20-42f1-b255-309d0d831a7a.png">

2022-03-03 02:04 UTC, viet-nv commented on src/constants/index.ts
> +  [ChainId.VELAS]: [...WETH_ONLY[ChainId.VELAS], DAI[ChainId.VELAS], USDC[ChainId.VELAS], USDT[ChainId.VELAS]],
Remove Dai if VLX do not have dai token

2022-03-03 02:09 UTC, namgold commented on src/constants/index.ts
> +  [ChainId.VELAS]: [ ...WETH_ONLY[ChainId.VELAS], DAI[ChainId.VELAS], USDC[ChainId.VELAS], USDT[ChainId.VELAS]],
It will causing error if we dont add this line, so what would I fill here?

2022-03-03 02:29 UTC, viet-nv commented on src/constants/index.ts
> +  [ChainId.VELAS]: [ ...WETH_ONLY[ChainId.VELAS], DAI[ChainId.VELAS], USDC[ChainId.VELAS], USDT[ChainId.VELAS]],
No, I mean remove DAI from this line, Like this:
`[ChainId.VELAS]: [ ...WETH_ONLY[ChainId.VELAS], USDC[ChainId.VELAS], USDT[ChainId.VELAS]],`

2022-03-08 08:06 UTC, viet-nv approved these changes

2022-03-08 08:10 UTC, merged