Encode by backend
KyberNetwork/dmm-interface pull request #928
Opened 2022-04-24 17:43 UTC by nguyenhuudungz

2022-04-27 02:43 UTC, tiendv89 commented on .env.production
> +REACT_APP_AGGREGATOR_API="https://aggregator-api.dev.kyberengineering.io"
Please double check this one

2022-04-27 02:48 UTC, tiendv89 commented on src/utils/aggregator.ts
> +    to: string | undefined,
You are missing the feeconfig params

2022-05-04 04:52 UTC, nguyenhuudungz commented on .env.production
> +REACT_APP_AGGREGATOR_API="https://aggregator-api.dev.kyberengineering.io"
Will change to prod before merging.

2022-05-04 04:52 UTC, nguyenhuudungz commented on src/utils/aggregator.ts
> +    to: string | undefined,
I added it.

2022-05-16 17:43 UTC, nguyenhuudungz commented on .env.production
> +REACT_APP_AGGREGATOR_API="https://aggregator-api.dev.kyberengineering.io"
done

2022-05-31 04:57 UTC, viet-nv requested changes

2022-05-31 04:57 UTC, viet-nv commented on src/hooks/useSwapV2Callback.ts
> +      console.log(`\n\n********************\n\n`)
remember to remove this

2022-05-31 04:57 UTC, viet-nv commented on src/hooks/useSwapV2Callback.ts
> +      console.log(`sendTransactionOption`, sendTransactionOption)
do we need this console.log?

2022-05-31 04:57 UTC, viet-nv commented on src/state/swap/reducer.ts
> +  feeConfig:
Remember to remove this when merge

2022-05-31 04:57 UTC, viet-nv commented on src/state/swap/reducer.ts
> +          // TODO (NHDz):
same as above

2022-05-31 04:57 UTC, viet-nv commented on src/utils/fee.ts
> +// TODO: Delete this function and logic of encoding in frontend after releasing it in backend.
remember this please

2022-06-10 09:26 UTC, closed without merging