feat: about page
KyberNetwork/dmm-interface pull request #954
Opened 2022-05-10 02:34 UTC by TienPQ149

2022-05-10 02:34 UTC, TienPQ149 commented
PR still WIP. Please do not merge

2022-05-12 06:58 UTC, viet-nv requested changes
Binance, gate.io, kucoin, tokyocrypto, upbit, wazirx,  => dùng chung 1 file (chuyển qua dùng react component đc thì tốt ạ)
các file svg còn lại tạo react component rồi đổi màu theo theme.

2022-05-12 06:58 UTC, viet-nv commented on src/assets/exchanges/binance_light.svg
> +<svg width="160" height="32" viewBox="0 0 160 32" fill="none" xmlns="http://www.w3.org/2000/svg">
e thấy file này vs file binance.svg giống nhau nên chắc dùng 1 cái thôi ạ. 
với cả cái nào 2 theme khác màu thì có thể dùng fill để đổi màu từ svg đc. như vậy sẽ đỡ công lưu assets

2022-05-12 07:17 UTC, viet-nv requested changes

2022-05-12 07:17 UTC, viet-nv commented on src/state/application/hooks.ts
> +export function useAboutPageModalToggle(): () => void {
cái này không cần đưa vào modal như này đâu a. đùng css hover dropdown là đc rồi ạ

2022-05-12 07:17 UTC, viet-nv commented on src/pages/App.tsx
> +const AboutKNC = lazy(() => import(/* webpackChunkName: 'about-page' */ './About/AboutKNC'))
cái chunk name này đổi sang about-knc đi a

2022-05-12 09:43 UTC, viet-nv approved these changes

2022-05-12 09:43 UTC, merged